[[group]]
markets = [
"ARSUFvUVR6p2ptvJoiuwiMEcobjC2BshrN2domGFiDV6", #PURCH Pump
"DCGJgtEWJxnD74sj81yoAFjji5g7H1VLtHaGyx2Gew6h", #PURCH Meteora DLMM
"3jJot32uiWA3wYmLSXhZ1UrM3tJCy3QxhEyaWVGTWD7R", #PURCH Meteora DLMM
"8Hr17Az18WtcHTo5QuuLXMCxQjGzkfpBxRrnStL2gipH", #Epstein Pump
"8bf1o4ifdTNxuQMvmRvWJmrVFa51scHGunedRrkNko9r", #Epstein Meteora DLMM
]
